comments = [
    'I love the news here',
    'I\'m enjoying wakanda right now',
    'This wakanda is a very good iniiative',
    'I\'m awaiting the day of my withdraw',
    'I hope i dont need refferals to withdraw',
    'Very good topic you have provided',
    'God bless our country',
    'Buhari should try this around',
    'The rigging for this election na die',
    'Thank God school don resume',
    'Very good initiative taken here',
   'This news is very interesting',
   'Shai, buhari don win o'
   'Please God save us from next level',
   'Very good topic, i must say',
   'Good topic, you have posted here',
   'I was very interested in this news',
   'I loved this post, very good',
   'Very good insight you have provided',
   'This news had a very good insight i must say',
   'I loved the information provided',
   'All these news are good to read',
   'I\'m liking wakanda so far',
   'I like this topics i must say',
   'I don\'t know what to say about this one',
   'I like reading this kind of news',
   'This post was fun to read',
   'Please, Buhari don\'t take us to the next level of suffering',
   'Can i withdraw without refferals',
   'I\'m gonna stick to wakanda',
   'If there is no refferals before you can withdraw, im so done with nnu',
   'Wakanda is really the best o',
   'God make Nigeria better again',
   'God take control of all the incidents in Nigeria',
   'Love the webdesign used on this page'

]